#!/bin/bash
# install docker on your computer
# Download Dockerfile etc from https://github.com/phnmnl/container-metabolab by:
# git clone https://github.com/phnmnl/container-metabolab
export pwd=$(pwd)
cd /ldata/reedma/container-metabolab  # directory containing dockerfile
docker image rm --force imeta_image$1
docker build -t imeta_image$1 .
cd $pwd
docker rm -f imeta_container$1
# path below is path to directory containing your container_script.ml
docker  run  -it --entrypoint=runMetabolab.sh -v  $(pwd):/mydata -w /mydata --name imeta_container$1 imeta_image$1 
